// Code generated by "genabi"; DO NOT EDIT.
package example

import (
	"github.com/indexsupply/x/abi"
	"github.com/indexsupply/x/abi/schema"
	"math/big"
)

type Transfer struct {
	From    [20]byte
	To      [20]byte
	Id      *big.Int
	Details [][]Details
}

func NewTransfer(item abi.Item) Transfer {
	x := Transfer{}
	detailsItem0 := item.At(0)
	details0 := make([][]Details, detailsItem0.Len())
	for i0 := 0; i0 < detailsItem0.Len(); i0++ {
		detailsItem1 := detailsItem0.At(i0)
		details1 := make([]Details, detailsItem1.Len())
		for i1 := 0; i1 < detailsItem1.Len(); i1++ {
			details1[i1] = NewDetails(detailsItem1.At(i1))
		}
		details0[i0] = details1
	}
	x.Details = details0
	return x
}

type Details struct {
	Other [20]byte
	Key   [32]byte
	Value []byte
	Geo   Geo
}

func NewDetails(item abi.Item) Details {
	x := Details{}
	x.Other = item.At(0).Address()
	x.Key = item.At(1).Bytes32()
	x.Value = item.At(2).Bytes()
	x.Geo = NewGeo(item.At(3))
	return x
}

type Geo struct {
	X uint8
	Y uint8
}

func NewGeo(item abi.Item) Geo {
	x := Geo{}
	x.X = item.At(0).Uint8()
	x.Y = item.At(1).Uint8()
	return x
}

// transfer(address,address,uint256,(address,bytes32,bytes,(uint8,uint8))[][])
// d18faf791871f68e0fa4d1faca22ed4bee53d9d7897b8e773ff616fffdced2be
var (
	TransferSignature = [32]byte{0xd1, 0x8f, 0xaf, 0x79, 0x18, 0x71, 0xf6, 0x8e, 0xf, 0xa4, 0xd1, 0xfa, 0xca, 0x22, 0xed, 0x4b, 0xee, 0x53, 0xd9, 0xd7, 0x89, 0x7b, 0x8e, 0x77, 0x3f, 0xf6, 0x16, 0xff, 0xfd, 0xce, 0xd2, 0xbe}
	TransferSchema    = schema.Parse("((address,bytes32,bytes,(uint8,uint8))[][])")
)

func MatchTransfer(l abi.Log) (Transfer, bool) {
	if TransferSignature != l.Topics[0] {
		return Transfer{}, false
	}
	item := abi.Decode(l.Data, TransferSchema)
	res := NewTransfer(item)
	res.From = abi.Bytes(l.Topics[1][:]).Address()
	res.To = abi.Bytes(l.Topics[2][:]).Address()
	res.Id = abi.Bytes(l.Topics[3][:]).BigInt()
	return res, true
}
