package abi

import (
	"bytes"
	"go/format"
	"text/template"
)

const ct = `
// Generated by github.com/indexsupply/x/cmd/genabi. DO NOT EDIT.

package {{.Package}}

{{- range $path, $name := .Imports}}
import {{$name}} {{printf "%q" $path}}
{{- end}}

{{range .Events}}
type {{.Name}} struct {
	{{- range .Inputs}}
		{{.Name}} string
	{{- end}}
}
{{end}}
`

func gen(name string, events []Event) ([]byte, error) {
	data := struct {
		Package string
		Imports map[string]string
		Events  []Event
	}{
		Package: name,
		Imports: map[string]string{},
		Events:  events,
	}
	var (
		b bytes.Buffer
		t = template.Must(template.New("letter").Parse(ct))
	)
	if err := t.Execute(&b, data); err != nil {
		return nil, err
	}
	return format.Source(b.Bytes())
}
